// Build step (run: `node build.js`). Generates two artifacts from the single sources of
// truth, so nothing is hand-copied:
//   1. schema.sql                  — D1 CREATE TABLE/INDEX, from tables.js
//   2. src/generated/process.gen.js — ../backend/process.js wrapped as a real function
//      (Cloudflare Workers forbid eval/new Function at runtime, so the wrap happens here,
//       at build time, not in the Worker).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { TABLES } from './tables.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const SQL_TYPE = { string: 'TEXT', number: 'REAL', boolean: 'INTEGER' };

// Columns worth indexing (the live "Get X" loaders filter on these). Correctness does not
// depend on indexes; they only keep the range/lookup queries fast on D1.
const INDEXES = {
  pos_sales: ['sale_date', 'client_id', 'invoice_no', 'customer_id'],
  pos_sale_items: ['sale_date', 'invoice_no'],
  pos_payments: ['pay_date', 'customer_id', 'supplier'],
  pos_purchases: ['purchase_date', 'purchase_no', 'supplier'],
  pos_approvals: ['status', 'request_id'],
  pos_expenses: ['expense_date'],
  pos_shifts: ['status', 'shift_date'],
  pos_repacks: ['repack_date'],
  pos_activity: ['act_date'],
  pos_bank_lines: ['account_id', 'period'],
  pos_returns: ['return_date', 'ref'],
  pos_photos: ['photo_id'],
};

function buildSchema() {
  const out = [
    '-- GENERATED by build.js from tables.js — do not edit by hand.',
    '-- D1 (SQLite) schema for the Khair POS code backend. `id` is the n8n system row id.',
    '',
  ];
  for (const [table, cols] of Object.entries(TABLES)) {
    const lines = ['  id INTEGER PRIMARY KEY AUTOINCREMENT'];
    for (const [col, type] of Object.entries(cols)) lines.push(`  ${col} ${SQL_TYPE[type]}`);
    out.push(`CREATE TABLE IF NOT EXISTS ${table} (`);
    out.push(lines.join(',\n'));
    out.push(');');
    for (const col of INDEXES[table] || []) {
      out.push(`CREATE INDEX IF NOT EXISTS idx_${table}_${col} ON ${table} (${col});`);
    }
    out.push('');
  }
  writeFileSync(join(HERE, 'schema.sql'), out.join('\n'));
  console.log('wrote schema.sql (%d tables)', Object.keys(TABLES).length);
}

function buildProcess() {
  const src = readFileSync(join(HERE, '..', 'backend', 'process.js'), 'utf8');
  const DECL = "const STORE_KEY = '__STORE_KEY__';";
  if (!src.includes(DECL)) throw new Error('process.js: expected first-line STORE_KEY declaration not found');
  // Remove the baked-placeholder declaration; STORE_KEY becomes a function parameter fed
  // from the Worker's env secret. Everything else is byte-identical to the n8n Process node.
  const body = src.replace(DECL, '');
  const gen = [
    '// GENERATED by build.js from ../../backend/process.js — do not edit by hand.',
    '// The n8n "Process" code node body, wrapped as a function. Top-level `return`',
    '// statements become returns of runProcess. `$` is the node accessor (src/db.js builds',
    '// it from D1); STORE_KEY is injected from the Worker secret.',
    '/* eslint-disable */',
    'export function runProcess($, STORE_KEY) {',
    body,
    '}',
    '',
  ].join('\n');
  mkdirSync(join(HERE, 'src', 'generated'), { recursive: true });
  writeFileSync(join(HERE, 'src', 'generated', 'process.gen.js'), gen);
  console.log('wrote src/generated/process.gen.js (%d bytes from process.js)', src.length);
}

buildSchema();
buildProcess();
