-- GENERATED by build.js from tables.js — do not edit by hand.
-- D1 (SQLite) schema for the Khair POS code backend. `id` is the n8n system row id.

CREATE TABLE IF NOT EXISTS pos_users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  role TEXT,
  pin_hash TEXT,
  active INTEGER,
  must_change INTEGER,
  master_hash TEXT,
  fail_count REAL,
  locked_until TEXT
);

CREATE TABLE IF NOT EXISTS pos_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  skey TEXT,
  svalue TEXT
);

CREATE TABLE IF NOT EXISTS pos_products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sku TEXT,
  name TEXT,
  category TEXT,
  unit TEXT,
  cost_price REAL,
  retail_price REAL,
  wholesale_price REAL,
  wholesale_min_qty REAL,
  stock REAL,
  min_stock REAL,
  active INTEGER,
  notes TEXT,
  image_updated TEXT,
  supplier TEXT,
  repack_from REAL,
  repack_qty REAL,
  shop_stock REAL,
  size TEXT,
  weight TEXT,
  exp_date TEXT,
  exp_none INTEGER
);

CREATE TABLE IF NOT EXISTS pos_customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  phone TEXT,
  type TEXT,
  address TEXT,
  notes TEXT,
  debt_balance REAL,
  wa_optin INTEGER,
  source TEXT,
  email TEXT,
  member INTEGER,
  member_no TEXT,
  member_since TEXT,
  visits REAL,
  last_visit TEXT,
  receipts_sent REAL
);

CREATE TABLE IF NOT EXISTS pos_sales (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  invoice_no TEXT,
  sale_date TEXT,
  sale_time TEXT,
  cashier TEXT,
  customer_id REAL,
  customer_name TEXT,
  customer_type TEXT,
  subtotal REAL,
  discount REAL,
  total REAL,
  total_cost REAL,
  profit REAL,
  payment_method TEXT,
  paid_amount REAL,
  debt_amount REAL,
  status TEXT,
  survey TEXT,
  notes TEXT,
  client_id TEXT,
  approved_by TEXT,
  exit_photo TEXT,
  exit_match TEXT,
  channel TEXT,
  promo_code TEXT,
  shift_id TEXT,
  survey_transcript TEXT,
  send_fee REAL
);
CREATE INDEX IF NOT EXISTS idx_pos_sales_sale_date ON pos_sales (sale_date);
CREATE INDEX IF NOT EXISTS idx_pos_sales_client_id ON pos_sales (client_id);
CREATE INDEX IF NOT EXISTS idx_pos_sales_invoice_no ON pos_sales (invoice_no);
CREATE INDEX IF NOT EXISTS idx_pos_sales_customer_id ON pos_sales (customer_id);

CREATE TABLE IF NOT EXISTS pos_sale_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  invoice_no TEXT,
  sale_date TEXT,
  product_id REAL,
  sku TEXT,
  name TEXT,
  qty REAL,
  unit_price REAL,
  price_type TEXT,
  cost_price REAL,
  line_total REAL,
  line_profit REAL,
  customer_name TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_sale_items_sale_date ON pos_sale_items (sale_date);
CREATE INDEX IF NOT EXISTS idx_pos_sale_items_invoice_no ON pos_sale_items (invoice_no);

CREATE TABLE IF NOT EXISTS pos_payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pay_date TEXT,
  customer_id REAL,
  customer_name TEXT,
  amount REAL,
  method TEXT,
  note TEXT,
  cashier TEXT,
  pay_id TEXT,
  direction TEXT,
  party_type TEXT,
  supplier TEXT,
  bank TEXT,
  transfer_ref TEXT,
  proof_photo_id TEXT,
  alloc TEXT,
  match_status TEXT,
  pay_time TEXT,
  account_id TEXT,
  slip_date TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_payments_pay_date ON pos_payments (pay_date);
CREATE INDEX IF NOT EXISTS idx_pos_payments_customer_id ON pos_payments (customer_id);
CREATE INDEX IF NOT EXISTS idx_pos_payments_supplier ON pos_payments (supplier);

CREATE TABLE IF NOT EXISTS pos_purchases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  purchase_date TEXT,
  supplier TEXT,
  product_id REAL,
  name TEXT,
  qty REAL,
  cost_price REAL,
  total REAL,
  note TEXT,
  user TEXT,
  photo_id TEXT,
  exp_date TEXT,
  purchase_no TEXT,
  match_status TEXT,
  match_notes TEXT,
  carrier_type TEXT,
  carrier_name TEXT,
  carrier_vehicle TEXT,
  carrier_phone TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_purchases_purchase_date ON pos_purchases (purchase_date);
CREATE INDEX IF NOT EXISTS idx_pos_purchases_purchase_no ON pos_purchases (purchase_no);
CREATE INDEX IF NOT EXISTS idx_pos_purchases_supplier ON pos_purchases (supplier);

CREATE TABLE IF NOT EXISTS pos_approvals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  request_id TEXT,
  client_id TEXT,
  created_at TEXT,
  cashier TEXT,
  customer_id REAL,
  customer_name TEXT,
  customer_debt_before REAL,
  total REAL,
  debt_amount REAL,
  summary TEXT,
  status TEXT,
  decided_by TEXT,
  decided_at TEXT,
  note TEXT,
  kind TEXT,
  ref TEXT,
  payload TEXT,
  approver_role TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_approvals_status ON pos_approvals (status);
CREATE INDEX IF NOT EXISTS idx_pos_approvals_request_id ON pos_approvals (request_id);

CREATE TABLE IF NOT EXISTS pos_expenses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  expense_date TEXT,
  category TEXT,
  amount REAL,
  note TEXT,
  user TEXT,
  photo_id TEXT,
  paid_from TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_expenses_expense_date ON pos_expenses (expense_date);

CREATE TABLE IF NOT EXISTS pos_shifts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shift_id TEXT,
  cashier TEXT,
  shift_date TEXT,
  opened_at TEXT,
  closed_at TEXT,
  status TEXT,
  opening_cash REAL,
  cash_sales REAL,
  cash_payments REAL,
  cash_in REAL,
  cash_out REAL,
  sales_count REAL,
  sales_total REAL,
  expected_cash REAL,
  counted_cash REAL,
  difference REAL,
  moves TEXT,
  note TEXT,
  transfer_sales REAL,
  qris_sales REAL,
  debt_sales REAL,
  items_qty REAL
);
CREATE INDEX IF NOT EXISTS idx_pos_shifts_status ON pos_shifts (status);
CREATE INDEX IF NOT EXISTS idx_pos_shifts_shift_date ON pos_shifts (shift_date);

CREATE TABLE IF NOT EXISTS pos_devices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  device_id TEXT,
  user TEXT,
  role TEXT,
  app TEXT,
  label TEXT,
  ua TEXT,
  ip TEXT,
  lat REAL,
  lng REAL,
  acc REAL,
  loc_status TEXT,
  loc_at TEXT,
  first_seen TEXT,
  last_seen TEXT,
  pings REAL,
  battery REAL
);

CREATE TABLE IF NOT EXISTS pos_repacks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  repack_id TEXT,
  repack_date TEXT,
  repack_time TEXT,
  user TEXT,
  from_product_id REAL,
  from_name TEXT,
  from_unit TEXT,
  from_qty REAL,
  to_product_id REAL,
  to_name TEXT,
  to_unit TEXT,
  to_qty REAL,
  pack_size REAL,
  expected_qty REAL,
  yield_pct REAL,
  loss_qty REAL,
  packaging_cost REAL,
  unit_cost REAL,
  exp_date TEXT,
  note TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_repacks_repack_date ON pos_repacks (repack_date);

CREATE TABLE IF NOT EXISTS pos_activity (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  act_id TEXT,
  at TEXT,
  act_date TEXT,
  user TEXT,
  role TEXT,
  kind TEXT,
  summary TEXT,
  ref TEXT,
  amount REAL,
  level TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_activity_act_date ON pos_activity (act_date);

CREATE TABLE IF NOT EXISTS pos_bank_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  line_id TEXT,
  account_id TEXT,
  period TEXT,
  seq REAL,
  line_date TEXT,
  description TEXT,
  amount REAL,
  ref TEXT,
  balance REAL,
  status TEXT,
  pay_id TEXT,
  note TEXT,
  imported_at TEXT,
  imported_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_bank_lines_account_id ON pos_bank_lines (account_id);
CREATE INDEX IF NOT EXISTS idx_pos_bank_lines_period ON pos_bank_lines (period);

CREATE TABLE IF NOT EXISTS pos_returns (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  return_id TEXT,
  kind TEXT,
  status TEXT,
  return_date TEXT,
  at TEXT,
  user TEXT,
  approved_by TEXT,
  request_id TEXT,
  ref TEXT,
  party_id REAL,
  party_name TEXT,
  bought_by TEXT,
  bought_date TEXT,
  returned_by TEXT,
  returned_by_phone TEXT,
  lines TEXT,
  qty_total REAL,
  value REAL,
  fee_pct REAL,
  fee REAL,
  refund REAL,
  refund_method TEXT,
  reason_code TEXT,
  reason_note TEXT,
  photo_id TEXT,
  out_doc_no TEXT,
  carrier_type TEXT,
  carrier_name TEXT,
  carrier_vehicle TEXT,
  carrier_phone TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_returns_return_date ON pos_returns (return_date);
CREATE INDEX IF NOT EXISTS idx_pos_returns_ref ON pos_returns (ref);

CREATE TABLE IF NOT EXISTS pos_photos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  photo_id TEXT,
  kind TEXT,
  ref TEXT,
  created_at TEXT,
  photo_date TEXT,
  user TEXT,
  drive_file_id TEXT,
  drive_url TEXT,
  extracted TEXT,
  match_status TEXT,
  match_notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_pos_photos_photo_id ON pos_photos (photo_id);

CREATE TABLE IF NOT EXISTS pos_shops (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shop_id TEXT,
  name TEXT,
  owner_name TEXT,
  phone TEXT,
  address TEXT,
  area TEXT,
  type TEXT,
  lat REAL,
  lng REAL,
  created_by TEXT,
  created_at TEXT,
  last_visit_at TEXT,
  visits REAL,
  status TEXT,
  customer_id REAL,
  next_visit TEXT,
  type_other TEXT,
  chain TEXT
);

CREATE TABLE IF NOT EXISTS pos_visits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  visit_id TEXT,
  client_id TEXT,
  user TEXT,
  visit_date TEXT,
  visit_time TEXT,
  shop_id TEXT,
  shop_name TEXT,
  lat REAL,
  lng REAL,
  acc REAL,
  distance_m REAL,
  outcome TEXT,
  notes TEXT,
  next_visit TEXT,
  photo_thumb TEXT,
  drive_url TEXT,
  rating REAL
);

CREATE TABLE IF NOT EXISTS pos_tracks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT,
  track_date TEXT,
  t TEXT,
  lat REAL,
  lng REAL,
  acc REAL,
  speed REAL,
  battery REAL
);

CREATE TABLE IF NOT EXISTS pos_field_days (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT,
  day_date TEXT,
  started_at TEXT,
  ended_at TEXT,
  start_lat REAL,
  start_lng REAL,
  end_lat REAL,
  end_lng REAL,
  km REAL,
  visits REAL,
  orders REAL,
  note TEXT
);

CREATE TABLE IF NOT EXISTS pos_field_orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_id TEXT,
  client_id TEXT,
  user TEXT,
  order_date TEXT,
  shop_id TEXT,
  shop_name TEXT,
  items TEXT,
  total REAL,
  notes TEXT,
  delivery_date TEXT,
  status TEXT,
  invoice_no TEXT,
  updated_by TEXT,
  order_time TEXT,
  status_note TEXT,
  payment_method TEXT
);

CREATE TABLE IF NOT EXISTS pos_product_images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  product_id REAL,
  image_base64 TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS pos_chat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel TEXT,
  cid TEXT,
  from_user TEXT,
  from_name TEXT,
  from_role TEXT,
  body TEXT,
  image TEXT,
  created_at TEXT,
  deleted INTEGER
);

CREATE TABLE IF NOT EXISTS pos_workers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  worker_id TEXT,
  name TEXT,
  phone TEXT,
  job TEXT,
  daily_wage REAL,
  active INTEGER,
  face_desc TEXT,
  face_thumb TEXT,
  consent_at TEXT,
  consent_by TEXT,
  created_at TEXT,
  created_by TEXT
);

CREATE TABLE IF NOT EXISTS pos_attendance (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  seq REAL,
  at TEXT,
  att_date TEXT,
  worker_id TEXT,
  worker_name TEXT,
  kind TEXT,
  score TEXT,
  face_ok INTEGER,
  device_id TEXT,
  by_user TEXT,
  lat TEXT,
  lng TEXT,
  dist_m TEXT,
  note TEXT,
  client_id TEXT,
  prev_hash TEXT,
  hash TEXT
);

CREATE TABLE IF NOT EXISTS pos_att_seals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  period TEXT,
  kind TEXT,
  count REAL,
  first_seq REAL,
  last_seq REAL,
  last_hash TEXT,
  summary TEXT,
  created_at TEXT,
  prev_hash TEXT,
  hash TEXT
);
