// Convert a JSON dump of the live n8n data tables into D1 INSERT statements.
//
// At cut-over, the live rows are exported through the n8n MCP (get_data_table_rows,
// paginated) into one JSON file shaped { "pos_users": [ {id, …cols}, … ], "pos_sales": […], … }
// — each row exactly as n8n returns it (booleans as true/false). This turns that into SQL,
// preserving ids (so foreign references like customer_id stay valid) and applying the same
// boolean→1/0 / object→JSON / null handling as the runtime writer.
//
// Usage:  node migrate/rows-to-sql.js dump.json > seed-data.sql
//   then: wrangler d1 execute khair_mart_jumla --remote --file worker/schema.sql
//         wrangler d1 execute khair_mart_jumla --remote --file seed-data.sql
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { TABLES, BOOL_COLS } from '../tables.js';

function sqlValue(table, col, v) {
  const isBool = (BOOL_COLS[table] || []).includes(col);
  if (v === null || v === undefined) return 'NULL';
  if (isBool || typeof v === 'boolean') return v === true || v === 1 ? '1' : '0';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'object') v = JSON.stringify(v);
  return "'" + String(v).replace(/'/g, "''") + "'"; // SQLite escapes a quote by doubling it
}

// Build the seed SQL from a dump object. Returns { sql, rows } (rows = total inserts).
export function rowsToSql(dump) {
  const out = ['-- GENERATED by migrate/rows-to-sql.js — live data snapshot for D1.', 'BEGIN TRANSACTION;'];
  let rows = 0;
  for (const [table, cols] of Object.entries(TABLES)) {
    const list = dump[table] || [];
    if (!list.length) continue;
    const colNames = ['id', ...Object.keys(cols)];
    for (const row of list) {
      const present = colNames.filter((c) => row[c] !== undefined);
      const values = present.map((c) => (c === 'id' ? String(row.id) : sqlValue(table, c, row[c])));
      out.push(`INSERT INTO ${table} (${present.join(', ')}) VALUES (${values.join(', ')});`);
      rows++;
    }
  }
  out.push('COMMIT;');
  return { sql: out.join('\n') + '\n', rows };
}

// CLI entry (only when run directly, not when imported by a test).
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const dumpPath = process.argv[2];
  if (!dumpPath) { console.error('usage: node migrate/rows-to-sql.js <dump.json> > seed-data.sql'); process.exit(1); }
  const dump = JSON.parse(readFileSync(dumpPath, 'utf8'));
  const { sql, rows } = rowsToSql(dump);
  process.stdout.write(sql);
  console.error(`seed-data.sql: ${rows} rows across ${Object.keys(dump).length} tables`);
}
